name: Build and Test
on:
  push:
    branches: 
      - main 
      - develop

permissions:
    contents: read 

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Restore dependencies
      run: dotnet restore
      continue-on-error: false

    - name: Build
      run: dotnet build
      continue-on-error: false

    - name: Test
      run: dotnet test
      continue-on-error: false

  trigger_tests_sonarcloud:
    needs: build_and_test
    name: Test and Analysis Code In Sonar Cloud
    uses: alexfariakof/Home_Broker_Chart/.github/workflows/test_analyse_in_Sonar_Cloud.yml@main
    secrets: inherit
