name: Build and Test
on:
  push:
    branches: 
      - main 
      - develop

permissions:
    contents: read 

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Cache .NET packages    
      uses: actions/cache@v3
      id: dotnet-cache
      with:
        path: ~/.nuget/packages
        key: dotnet-packages-${{ github.repository }}
        restore-keys: dotnet-packages-${{ github.repository }}

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      if: steps.dotnet-cache.outputs.cache-hit != 'true'
      with:
        dotnet-version: 7.0.x
    
    - name: Restore dependencies
      run: dotnet restore
      continue-on-error: false

    - name: Build .Net
      run: dotnet build  --restore
      continue-on-error: false

    - name: Test .Net
      run: dotnet test
      continue-on-error: false

    - name: Install Npm dependencies
      run: |
        cd angularapp
        npm install npm@latest
        npm install -g @angular/cli
        npm install
    
    - name: Build Angular
      run: |

    - name: Test Angula
      run: |
        cd angularapp
        npm run test:coverage

  trigger_tests_sonarcloud:
    needs: build_and_test
    name: Test and Analysis Code In Sonar Cloud
    uses: alexfariakof/Home_Broker_Chart/.github/workflows/test_analyse_in_Sonar_Cloud.yml@develop
    secrets: inherit
